module Paya
  class Configuration
    attr_accessor :user_name,
                  :password,
                  :production,
                  :ccd_terminal_id,
                  :ppd_terminal_id,
                  :tel_terminal_id,
                  :web_terminal_id,

                  :ccd_guaranteed_credit_debit_check_no_verification_dl_optional_terminal_id,
                  :ccd_guaranteed_credit_debit_check_no_verification_dl_required_terminal_id,
                  :ccd_guaranteed_credit_debit_check_verification_identity_verification_dl_optional_terminal_id,
                  :ccd_guaranteed_credit_debit_check_verification_identity_verification_dl_required_terminal_id,
                  :ccd_guaranteed_credit_debit_check_verification_only_dl_optional_terminal_id,
                  :ccd_guaranteed_credit_debit_check_verification_only_dl_required_terminal_id,
                  :ccd_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id,
                  :ccd_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id,

                  :ccd_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id,
                  :ccd_guaranteed_debit_only_check_no_verification_dl_required_terminal_id,
                  :ccd_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id,
                  :ccd_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id,
                  :ccd_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id,
                  :ccd_guaranteed_debit_only_check_verification_only_dl_required_terminal_id,
                  :ccd_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,
                  :ccd_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,

                  :ccd_non_guaranteed_credit_debit_check_no_verification_dl_optional_terminal_id,
                  :ccd_non_guaranteed_credit_debit_check_no_verification_dl_required_terminal_id,
                  :ccd_non_guaranteed_credit_debit_check_verification_identity_verification_dl_optional_terminal_id,
                  :ccd_non_guaranteed_credit_debit_check_verification_identity_verification_dl_required_terminal_id,
                  :ccd_non_guaranteed_credit_debit_check_verification_only_dl_optional_terminal_id,
                  :ccd_non_guaranteed_credit_debit_check_verification_only_dl_required_terminal_id,
                  :ccd_non_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id,
                  :ccd_non_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id,

                  :ccd_non_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id,
                  :ccd_non_guaranteed_debit_only_check_no_verification_dl_required_terminal_id,
                  :ccd_non_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id,
                  :ccd_non_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id,
                  :ccd_non_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id,
                  :ccd_non_guaranteed_debit_only_check_verification_only_dl_required_terminal_id,
                  :ccd_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,
                  :ccd_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,

                  :ppd_guaranteed_credit_debit_check_no_verification_dl_optional_terminal_id,
                  :ppd_guaranteed_credit_debit_check_no_verification_dl_required_terminal_id,
                  :ppd_guaranteed_credit_debit_check_verification_identity_verification_dl_optional_terminal_id,
                  :ppd_guaranteed_credit_debit_check_verification_identity_verification_dl_required_terminal_id,
                  :ppd_guaranteed_credit_debit_check_verification_only_dl_optional_terminal_id,
                  :ppd_guaranteed_credit_debit_check_verification_only_dl_required_terminal_id,
                  :ppd_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id,
                  :ppd_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id,

                  :ppd_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id,
                  :ppd_guaranteed_debit_only_check_no_verification_dl_required_terminal_id,
                  :ppd_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id,
                  :ppd_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id,
                  :ppd_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id,
                  :ppd_guaranteed_debit_only_check_verification_only_dl_required_terminal_id,
                  :ppd_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,
                  :ppd_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,

                  :ppd_non_guaranteed_credit_debit_check_no_verification_dl_optional_terminal_id,
                  :ppd_non_guaranteed_credit_debit_check_no_verification_dl_required_terminal_id,
                  :ppd_non_guaranteed_credit_debit_check_verification_identity_verification_dl_optional_terminal_id,
                  :ppd_non_guaranteed_credit_debit_check_verification_identity_verification_dl_required_terminal_id,
                  :ppd_non_guaranteed_credit_debit_check_verification_only_dl_optional_terminal_id,
                  :ppd_non_guaranteed_credit_debit_check_verification_only_dl_required_terminal_id,
                  :ppd_non_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id,
                  :ppd_non_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id,

                  :ppd_non_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id,
                  :ppd_non_guaranteed_debit_only_check_no_verification_dl_required_terminal_id,
                  :ppd_non_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id,
                  :ppd_non_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id,
                  :ppd_non_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id,
                  :ppd_non_guaranteed_debit_only_check_verification_only_dl_required_terminal_id,
                  :ppd_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,
                  :ppd_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,

                  :tel_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id,
                  :tel_guaranteed_debit_only_check_no_verification_dl_required_terminal_id,
                  :tel_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id,
                  :tel_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id,
                  :tel_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id,
                  :tel_guaranteed_debit_only_check_verification_only_dl_required_terminal_id,
                  :tel_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,
                  :tel_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,

                  :tel_non_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id,
                  :tel_non_guaranteed_debit_only_check_no_verification_dl_required_terminal_id,
                  :tel_non_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id,
                  :tel_non_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id,
                  :tel_non_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id,
                  :tel_non_guaranteed_debit_only_check_verification_only_dl_required_terminal_id,
                  :tel_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,
                  :tel_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,

                  :web_non_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id,
                  :web_non_guaranteed_debit_only_check_no_verification_dl_required_terminal_id,
                  :web_non_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id,
                  :web_non_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id,
                  :web_non_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id,
                  :web_non_guaranteed_debit_only_check_verification_only_dl_required_terminal_id,
                  :web_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id,
                  :web_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id

    def initialize
      @production = false
    end
  end
end