require 'paya'
require 'securerandom'

Paya.configure do |config|
  config.user_name = "YOUR-USER-NAME"
  config.password = "YOUR-PASSWORD"
  config.production = false

  config.ccd_terminal_id = 000000
  config.ppd_terminal_id = 000000
  config.web_terminal_id = 000000
  config.tel_terminal_id = 000000

  # CCD detailed terminal id's
  config.ccd_guaranteed_credit_debit_check_no_verification_dl_optional_terminal_id = 1910
  config.ccd_guaranteed_credit_debit_check_no_verification_dl_required_terminal_id = 1911
  config.ccd_guaranteed_credit_debit_check_verification_identity_verification_dl_optional_terminal_id = 1912
  config.ccd_guaranteed_credit_debit_check_verification_identity_verification_dl_required_terminal_id = 1913
  config.ccd_guaranteed_credit_debit_check_verification_only_dl_optional_terminal_id = 1914
  config.ccd_guaranteed_credit_debit_check_verification_only_dl_required_terminal_id = 1915
  config.ccd_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id = 1916
  config.ccd_guaranteed_credit_debit_identity_verification_only_dl_required_terminal_id = 1917

  config.ccd_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id = 1710
  config.ccd_guaranteed_debit_only_check_no_verification_dl_required_terminal_id = 1711
  config.ccd_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id = 1712
  config.ccd_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id = 1713
  config.ccd_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id = 1714
  config.ccd_guaranteed_debit_only_check_verification_only_dl_required_terminal_id = 1715
  config.ccd_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id = 1716
  config.ccd_guaranteed_debit_only_identity_verification_only_dl_required_terminal_id = 1717

  config.ccd_non_guaranteed_credit_debit_check_no_verification_dl_optional_terminal_id = 2910
  config.ccd_non_guaranteed_credit_debit_check_no_verification_dl_required_terminal_id = 2911
  config.ccd_non_guaranteed_credit_debit_check_verification_identity_verification_dl_optional_terminal_id = 2912
  config.ccd_non_guaranteed_credit_debit_check_verification_identity_verification_dl_required_terminal_id = 2913
  config.ccd_non_guaranteed_credit_debit_check_verification_only_dl_optional_terminal_id = 2914
  config.ccd_non_guaranteed_credit_debit_check_verification_only_dl_required_terminal_id = 2915
  config.ccd_non_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id = 2916
  config.ccd_non_guaranteed_credit_debit_identity_verification_only_dl_required_terminal_id = 2917

  config.ccd_non_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id = 2710
  config.ccd_non_guaranteed_debit_only_check_no_verification_dl_required_terminal_id = 2711
  config.ccd_non_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id = 2712
  config.ccd_non_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id = 2713
  config.ccd_non_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id = 2714
  config.ccd_non_guaranteed_debit_only_check_verification_only_dl_required_terminal_id = 2715
  config.ccd_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id = 2716
  config.ccd_non_guaranteed_debit_only_identity_verification_only_dl_required_terminal_id = 2717

  # PPD detailed terminal id's
  config.ppd_guaranteed_credit_debit_check_no_verification_dl_optional_terminal_id = 1810
  config.ppd_guaranteed_credit_debit_check_no_verification_dl_required_terminal_id = 1811
  config.ppd_guaranteed_credit_debit_check_verification_identity_verification_dl_optional_terminal_id = 1812
  config.ppd_guaranteed_credit_debit_check_verification_identity_verification_dl_required_terminal_id = 1813
  config.ppd_guaranteed_credit_debit_check_verification_only_dl_optional_terminal_id = 1814
  config.ppd_guaranteed_credit_debit_check_verification_only_dl_required_terminal_id = 1815
  config.ppd_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id = 1816
  config.ppd_guaranteed_credit_debit_identity_verification_only_dl_required_terminal_id = 1817

  config.ppd_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id = 1010
  config.ppd_guaranteed_debit_only_check_no_verification_dl_required_terminal_id = 1011
  config.ppd_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id = 1012
  config.ppd_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id = 1013
  config.ppd_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id = 1014
  config.ppd_guaranteed_debit_only_check_verification_only_dl_required_terminal_id = 1015
  config.ppd_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id = 1016
  config.ppd_guaranteed_debit_only_identity_verification_only_dl_required_terminal_id = 1017

  config.ppd_non_guaranteed_credit_debit_check_no_verification_dl_optional_terminal_id = 2810
  config.ppd_non_guaranteed_credit_debit_check_no_verification_dl_required_terminal_id = 2811
  config.ppd_non_guaranteed_credit_debit_check_verification_identity_verification_dl_optional_terminal_id = 2812
  config.ppd_non_guaranteed_credit_debit_check_verification_identity_verification_dl_required_terminal_id = 2813
  config.ppd_non_guaranteed_credit_debit_check_verification_only_dl_optional_terminal_id = 2814
  config.ppd_non_guaranteed_credit_debit_check_verification_only_dl_required_terminal_id = 2815
  config.ppd_non_guaranteed_credit_debit_identity_verification_only_dl_optional_terminal_id = 2816
  config.ppd_non_guaranteed_credit_debit_identity_verification_only_dl_required_terminal_id = 2817

  config.ppd_non_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id = 2010
  config.ppd_non_guaranteed_debit_only_check_no_verification_dl_required_terminal_id = 2011
  config.ppd_non_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id = 2012
  config.ppd_non_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id = 2013
  config.ppd_non_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id = 2014
  config.ppd_non_guaranteed_debit_only_check_verification_only_dl_required_terminal_id = 2015
  config.ppd_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id = 2016
  config.ppd_non_guaranteed_debit_only_identity_verification_only_dl_required_terminal_id = 2017

  config.web_non_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id = 2310
  config.web_non_guaranteed_debit_only_check_no_verification_dl_required_terminal_id = 2311
  config.web_non_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id = 2312
  config.web_non_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id = 2313
  config.web_non_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id = 2314
  config.web_non_guaranteed_debit_only_check_verification_only_dl_required_terminal_id = 2315
  config.web_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id = 2316
  config.web_non_guaranteed_debit_only_identity_verification_only_dl_required_terminal_id = 2317

  # TEL detailed terminal id's
  config.tel_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id = 1210
  config.tel_guaranteed_debit_only_check_no_verification_dl_required_terminal_id = 1211
  config.tel_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id = 1212
  config.tel_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id = 1213
  config.tel_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id = 1214
  config.tel_guaranteed_debit_only_check_verification_only_dl_required_terminal_id = 1215
  config.tel_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id = 1216
  config.tel_guaranteed_debit_only_identity_verification_only_dl_required_terminal_id = 1217

  config.tel_non_guaranteed_debit_only_check_no_verification_dl_optional_terminal_id = 2210
  config.tel_non_guaranteed_debit_only_check_no_verification_dl_required_terminal_id = 2211
  config.tel_non_guaranteed_debit_only_check_verification_identity_verification_dl_optional_terminal_id = 2212
  config.tel_non_guaranteed_debit_only_check_verification_identity_verification_dl_required_terminal_id = 2213
  config.tel_non_guaranteed_debit_only_check_verification_only_dl_optional_terminal_id = 2214
  config.tel_non_guaranteed_debit_only_check_verification_only_dl_required_terminal_id = 2215
  config.tel_non_guaranteed_debit_only_identity_verification_only_dl_optional_terminal_id = 2216
  config.tel_non_guaranteed_debit_only_identity_verification_only_dl_required_terminal_id = 2217


end